/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2francobarrarogerbalan;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import java.awt.*;
import java.awt.event.ActionEvent;

public class GUI extends javax.swing.JFrame {

    // --- VARIABLES GLOBALES ---
    private FileManager fileManager;
    private Timer simulationTimer;
    private GestorSesion gestorSesion; // Para manejar Admin/Usuario
    
    // Componentes visuales
    private JTree treeDirectorios;
    private DefaultTreeModel treeModel;
    private JPanel panelDisco;
    private JTable tablaProcesos;
    private DefaultTableModel tableModelProcesos;
    private JLabel lblEstadoDisco;
    
    // NUEVO: Componentes de Sesión
    private JLabel lblUsuario;
    private JButton btnCambiarUsuario;
    private JButton btnGuardar;
    private JButton btnCargar;
    public GUI() {

        initComponents();
    }
/**
     * Constructor personalizado que recibe el FileManager
     */
    public GUI(FileManager fileManager) {
        // 1. Inicializa lo básico de NetBeans
        initComponents();
       this.fileManager = fileManager;
        this.gestorSesion = new GestorSesion(); 
        
        // --- EL ARREGLO MÁGICO ---
        // Borramos todo lo que NetBeans haya puesto por defecto (paneles vacíos, layouts rotos)
        // Esto limpia el lienzo para que podamos pintar nuestro diseño.
        this.getContentPane().removeAll();
        
        // 2. Cargamos nuestro diseño oscuro
        iniciarComponentesDinamicos();
        
        // 3. Forzamos a la ventana a reconocer los cambios
        this.revalidate();
        this.repaint();
        
        // 4. Iniciamos el Timer de refresco
        simulationTimer = new Timer(500, (ActionEvent e) -> {
            actualizarVistas();
        });
        simulationTimer.start();
        
        // 5. Centrar ventana
        this.setLocationRelativeTo(null);
        actualizarVistas();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
private NodeDirectory getDirectorioSeleccionado() {
        DefaultMutableTreeNode nodoVisual = (DefaultMutableTreeNode) treeDirectorios.getLastSelectedPathComponent();
        
        if (nodoVisual == null) {
            return fileManager.getRoot(); // Si no hay nada, usa ROOT
        }
        
        // Recuperamos el objeto real (Node) que guardamos dentro del nodo visual
        Object objetoReal = nodoVisual.getUserObject();
        
        if (objetoReal instanceof NodeDirectory) {
            return (NodeDirectory) objetoReal;
        } else if (objetoReal instanceof NodeFile) {
            // Si seleccionas un archivo, devolvemos su carpeta padre
            return ((NodeFile) objetoReal).getParent();
        }
        
        return fileManager.getRoot();
    }

    // ---------------------------------------------------------
    // LÓGICA DE ACCIONES (BOTONES)
    // ---------------------------------------------------------

    private void accionCrearArchivo() {
        // 1. Detectar dónde guardar (Subcarpeta o Root)
        NodeDirectory carpetaDestino = getDirectorioSeleccionado();
        
        JTextField nombreField = new JTextField();
        JTextField tamField = new JTextField();
        Object[] message = {
            "Carpeta: " + carpetaDestino.getName(), // Mostramos dónde se va a guardar
            "Nombre del Archivo:", nombreField,
            "Tamaño (Bloques):", tamField
        };

        int option = JOptionPane.showConfirmDialog(this, message, "Crear Archivo", JOptionPane.OK_CANCEL_OPTION);

        if (option == JOptionPane.OK_OPTION) {
            try {
                String nombre = nombreField.getText();
                int tam = Integer.parseInt(tamField.getText());
                
                if (tam <= 0) throw new NumberFormatException();

                // 2. Crear Objeto Lógico EN LA CARPETA SELECCIONADA
                NodeFile nuevo = new NodeFile(nombre, carpetaDestino, tam);
                carpetaDestino.addChild(nuevo); // <--- CAMBIO IMPORTANTE: Se agrega a la carpeta destino
                
                // 3. Crear Proceso y Solicitud
                proyecto2francobarrarogerbalan.Process proceso = fileManager.getProcessManager().createProcess("Crear " + nombre);
                
                IORequests request = new IORequests(proceso, TipoSolicitud.CREAR, nuevo.getPath(), tam, 0);
                request.setArchivoPendiente(nuevo);
                
                fileManager.getPlanificador().addRequest(request);
                JOptionPane.showMessageDialog(this, "Solicitud enviada.");
                actualizarVistas();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error: Datos inválidos.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void accionCrearCarpeta() {
        NodeDirectory carpetaDestino = getDirectorioSeleccionado();
        String nombre = JOptionPane.showInputDialog(this, "Crear carpeta en: " + carpetaDestino.getName() + "\nNombre:");
        
        if (nombre != null && !nombre.trim().isEmpty()) {
             // Crear carpeta dentro de la seleccionada
             carpetaDestino.addChild(new NodeDirectory(nombre, carpetaDestino));
             actualizarVistas();
        }
    }

    private void accionEliminarArchivo() {
        // ---------------------------------------------------------
        // SOLUCIÓN PROBLEMA 2: VALIDACIÓN DE ADMIN
        // ---------------------------------------------------------
        if (!gestorSesion.isAdmin()) {
            JOptionPane.showMessageDialog(this, "ACCESO DENEGADO: Solo el Administrador puede eliminar.", "Permisos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // ---------------------------------------------------------
        // SOLUCIÓN PROBLEMA 1: ELIMINAR EL OBJETO CORRECTO
        // ---------------------------------------------------------
        DefaultMutableTreeNode nodoVisual = (DefaultMutableTreeNode) treeDirectorios.getLastSelectedPathComponent();
        
        if (nodoVisual == null || nodoVisual.isRoot()) {
            JOptionPane.showMessageDialog(this, "Seleccione un archivo para eliminar.");
            return;
        }
        
        // Obtenemos el objeto REAL directamente del árbol (sin buscar por nombre)
        Object objetoReal = nodoVisual.getUserObject();
        
        if (objetoReal instanceof Node) {
            Node nodoABorrar = (Node) objetoReal;
            
            int confirm = JOptionPane.showConfirmDialog(this, "¿Eliminar " + nodoABorrar.getName() + "?");
            if (confirm == JOptionPane.YES_OPTION) {
                
                proyecto2francobarrarogerbalan.Process proceso = fileManager.getProcessManager().createProcess("Borrar " + nodoABorrar.getName());
                
                IORequests request = new IORequests(proceso, TipoSolicitud.ELIMINAR, nodoABorrar.getPath(), 0, 0);
                request.setArchivoPendiente(nodoABorrar);
                
                fileManager.getPlanificador().addRequest(request);
                JOptionPane.showMessageDialog(this, "Solicitud de eliminación enviada.");
            }
        }
    }

    private void accionCambiarUsuario() {
        if (gestorSesion.isAdmin()) {
            gestorSesion.setModoActual(ModoUsuario.USUARIO);
        } else {
            String pass = JOptionPane.showInputDialog("Contraseña de Admin (admin):");
            if ("admin".equals(pass)) {
                gestorSesion.setModoActual(ModoUsuario.ADMINISTRADOR);
            } else if (pass != null) {
                JOptionPane.showMessageDialog(this, "Contraseña incorrecta.");
            }
        }
        actualizarInfoUsuario();
    }
    
    private void accionGuardar() {
        // Asegúrate de que el nombre del archivo sea el que prefieras
        if (GestorPersistencia.guardarEstado(fileManager, "simulador.dat")) {
            JOptionPane.showMessageDialog(this, "Estado guardado correctamente.");
        }
    }

    private void accionCargar() {
        FileManager cargado = GestorPersistencia.cargarEstado("simulador.dat");
        if (cargado != null) {
            this.fileManager = cargado;
            treeModel.setRoot(crearArbolVisual(fileManager.getRoot()));
            treeModel.reload();
            JOptionPane.showMessageDialog(this, "Estado cargado exitosamente.");
        }
    }

    // ---------------------------------------------------------
    // MÉTODOS DE ACTUALIZACIÓN VISUAL
    // ---------------------------------------------------------

    void actualizarVistas() {
        if (fileManager == null) return;
        
        // Refrescar Árbol
        DefaultMutableTreeNode rootVisual = crearArbolVisual(fileManager.getRoot());
        treeModel.setRoot(rootVisual);
        treeModel.reload();
        
        // Expandir filas
        for (int i = 0; i < treeDirectorios.getRowCount(); i++) {
            treeDirectorios.expandRow(i);
        }
        
        // Refrescar Tabla
        tableModelProcesos.setRowCount(0);
        NodeList<proyecto2francobarrarogerbalan.Process> current = fileManager.getProcessManager().getProcessTable().getHead();
        while (current != null) {
            proyecto2francobarrarogerbalan.Process p = current.getData();
            tableModelProcesos.addRow(new Object[]{p.getPid(), p.getName(), p.getState()});
            current = current.getNext();
        }
        
        // Refrescar Disco
        actualizarMapaDisco();
    }
    
    private void actualizarInfoUsuario() {
        if (gestorSesion.isAdmin()) {
            lblUsuario.setText("Modo: ADMINISTRADOR");
            lblUsuario.setForeground(Color.RED);
        } else {
            lblUsuario.setText("Modo: USUARIO");
            lblUsuario.setForeground(Color.CYAN); // O el color que prefieras
        }
    }

    private DefaultMutableTreeNode crearArbolVisual(Node nodoLogico) {
        // <--- CAMBIO CRÍTICO: Pasamos el OBJETO nodoLogico, no solo el nombre
        // Esto permite que al seleccionar en el árbol recuperemos el objeto real.
        DefaultMutableTreeNode nodoVisual = new DefaultMutableTreeNode(nodoLogico);
        
        if (nodoLogico instanceof NodeDirectory) {
            NodeDirectory dir = (NodeDirectory) nodoLogico;
            NodeList<Node> current = dir.getChildren().getHead();
            while (current != null) {
                nodoVisual.add(crearArbolVisual(current.getData()));
                current = current.getNext();
            }
        }
        return nodoVisual;
    }
    
    private void actualizarMapaDisco() {
        panelDisco.removeAll();
        Block[] bloques = fileManager.getDisco().getBlocks();
        int libres = 0;
        
        for (int i = 0; i < bloques.length; i++) {
            JPanel p = new JPanel();
            // Borde gris oscuro para que se vea la rejilla
            p.setBorder(BorderFactory.createLineBorder(new Color(60, 60, 60))); 
            
            if (bloques[i].isFree()) {
                p.setBackground(new Color(46, 204, 113)); // Verde
                libres++;
            } else {
                p.setBackground(new Color(231, 76, 60)); // Rojo
            }
            panelDisco.add(p);
        }
        lblEstadoDisco.setText("Bloques Libres: " + libres + " / " + bloques.length);
        panelDisco.revalidate();
        panelDisco.repaint();
    }

    // ---------------------------------------------------------
    // CONFIGURACIÓN VISUAL INICIAL (COLORES Y PANELES)
    // ---------------------------------------------------------
    
    // Colores de Alto Contraste
    private final Color COLOR_FONDO = new Color(18, 18, 18);
    private final Color COLOR_PANEL = new Color(35, 35, 35);
    private final Color COLOR_ACCENTO = new Color(52, 152, 219);

private void iniciarComponentesDinamicos() {
        setTitle("Simulador SO - Proyecto 2");
        setSize(1280, 720);
        
        // Aseguramos que usamos BorderLayout
        this.getContentPane().setLayout(new BorderLayout(10, 10));
        this.getContentPane().setBackground(COLOR_FONDO);

        // --- 1. Panel Superior (Usuario + Persistencia) ---
        JPanel panelTop = new JPanel(new FlowLayout(FlowLayout.LEFT));
        panelTop.setBackground(COLOR_PANEL);
        
        lblUsuario = new JLabel("Modo: USUARIO");
        lblUsuario.setFont(new Font("Segoe UI", Font.BOLD, 14));
        
        btnCambiarUsuario = crearBotonModerno("Cambiar Sesión");
        btnGuardar = crearBotonModerno("Guardar");
        btnCargar = crearBotonModerno("Cargar");
        
        btnCambiarUsuario.addActionListener(e -> accionCambiarUsuario());
        btnGuardar.addActionListener(e -> accionGuardar());
        btnCargar.addActionListener(e -> accionCargar());
        
        panelTop.add(lblUsuario);
        panelTop.add(Box.createHorizontalStrut(20));
        panelTop.add(btnCambiarUsuario);
        panelTop.add(Box.createHorizontalStrut(50));
        panelTop.add(btnGuardar);
        panelTop.add(btnCargar);
        
        add(panelTop, BorderLayout.NORTH);

        // --- 2. Panel Izquierdo (Árbol) ---
        treeModel = new DefaultTreeModel(new DefaultMutableTreeNode("Root"));
        treeDirectorios = new JTree(treeModel);
        estilizarArbol(treeDirectorios);
        
        JScrollPane scrollTree = new JScrollPane(treeDirectorios);
        scrollTree.setPreferredSize(new Dimension(250, 0));
        scrollTree.setBorder(null);
        
        JPanel panelIzq = crearPanelModerno("EXPLORADOR");
        panelIzq.add(scrollTree, BorderLayout.CENTER);
        add(panelIzq, BorderLayout.WEST);

        // --- 3. Panel Central (Disco) ---
        panelDisco = new JPanel(new GridLayout(16, 16, 1, 1));
        panelDisco.setBackground(COLOR_PANEL);
        
        JPanel panelCentro = crearPanelModerno("MAPA DE BITS");
        panelCentro.add(new JScrollPane(panelDisco), BorderLayout.CENTER);
        add(panelCentro, BorderLayout.CENTER);

        // --- 4. Panel Inferior (Procesos + Botones) ---
        JPanel panelInf = new JPanel(new BorderLayout(10, 0));
        panelInf.setBackground(COLOR_FONDO);
        panelInf.setPreferredSize(new Dimension(0, 200));
        
        // Tabla
        String[] col = {"PID", "Proceso", "Estado"};
        tableModelProcesos = new DefaultTableModel(col, 0);
        tablaProcesos = new JTable(tableModelProcesos);
        estilizarTabla(tablaProcesos);
        
        JPanel panelTabla = crearPanelModerno("PROCESOS");
        panelTabla.add(new JScrollPane(tablaProcesos), BorderLayout.CENTER);
        
        // Botones Acciones
        JPanel panelBtn = crearPanelModerno("ACCIONES");
        panelBtn.setPreferredSize(new Dimension(200, 0));
        JPanel gridBtn = new JPanel(new GridLayout(4, 1, 5, 10));
        gridBtn.setBackground(COLOR_PANEL);
        
        JButton btnCrear = crearBotonModerno("Crear Archivo");
        JButton btnCarpeta = crearBotonModerno("Crear Carpeta");
        JButton btnEliminar = crearBotonModerno("Eliminar");
        lblEstadoDisco = new JLabel("Libres: ...");
        lblEstadoDisco.setForeground(Color.WHITE);
        
        btnCrear.addActionListener(e -> accionCrearArchivo());
        btnCarpeta.addActionListener(e -> accionCrearCarpeta());
        btnEliminar.addActionListener(e -> accionEliminarArchivo());
        
        gridBtn.add(lblEstadoDisco);
        gridBtn.add(btnCrear);
        gridBtn.add(btnCarpeta);
        gridBtn.add(btnEliminar);
        panelBtn.add(gridBtn, BorderLayout.CENTER);
        
        panelInf.add(panelTabla, BorderLayout.CENTER);
        panelInf.add(panelBtn, BorderLayout.EAST);
        
        add(panelInf, BorderLayout.SOUTH);
        
        actualizarInfoUsuario();
    }

    private JPanel crearPanelModerno(String titulo) {
        JPanel p = new JPanel(new BorderLayout());
        p.setBackground(COLOR_PANEL);
        p.setBorder(BorderFactory.createTitledBorder(null, titulo, 0, 0, new Font("Segoe UI", Font.BOLD, 12), Color.WHITE));
        return p;
    }
    
    private JButton crearBotonModerno(String txt) {
        JButton b = new JButton(txt);
        b.setBackground(COLOR_ACCENTO);
        b.setForeground(Color.WHITE);
        b.setFocusPainted(false);
        b.setFont(new Font("Segoe UI", Font.BOLD, 12));
        return b;
    }
    
    private void estilizarArbol(JTree t) {
        t.setBackground(COLOR_PANEL);
        t.setForeground(Color.WHITE);
    }
    
    private void estilizarTabla(JTable t) {
        t.setBackground(COLOR_PANEL);
        t.setForeground(Color.WHITE);
        t.getTableHeader().setBackground(new Color(50,50,50));
        t.getTableHeader().setForeground(COLOR_ACCENTO);
    }

    // --- generated code --             
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

